name: ClearLagg
main: ClearLagg\Loader
version: 1.1.0
api: 1.0.0
author: LegendOfMCPE
website: https://github.com/LegendOfMCPE/ClearLagg
description: "Port of Bukkit ClearLagg for Genisys Servers"
permissions:
  clearlagg:
      default: op
      description: "Allows access to the clearlagg command."
